# Generated by Django 2.1 on 2020-01-18 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('alias', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Heroes',
            },
        ),
    ]
